name: LM_Items
version: ${project.version}
main: io.github.stumper66.lm_items.LM_Items
softdepend:
  - ExecutableItems
  - SCore
  - MMOItems
  - Coins
  - eco
  - EcoArmor
  - EcoCrates
  - EcoItems
  - Reforges
  - Talismans
  - MagicHealth
  - CustomCrafting
  - WolfyUtilities
  - ExcellentCrates
  - ItemEdit
  - Oraxen
  - MythicMobs
  - CompatWeaponryPlus
api-version: '1.16'
load: POSTWORLD
author: stumper66
description: ${project.description}
website: 'https://github.com/stumper66/LM_Items'
folia-supported: true

commands:
  lm_items:
    description: Manage LM Items
    aliases: [ lmi ]

permissions:
  lm_items.*:
    description: 'Access to all LM Items.'
    default: op
